name: openvidu-angular E2E
on:
  push:
    paths:
      - 'openvidu-components-angular/**'
  pull_request:
    branches:
      - master
  workflow_dispatch:


jobs:

  openvidu_angular_e2e:
    name: E2E tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Run Selenium Chromedriver
      run: docker run -d --shm-size="2g" --network host selenium/standalone-chrome:latest
    - name: Run openvidu-server-kms
      run: docker run -p 4443:4443 --rm -d -e OPENVIDU_SECRET=MY_SECRET openvidu/openvidu-server-kms:latest
    - name: Install dependencies
      run: npm install --prefix openvidu-components-angular
    - name: Build openvidu-angular
      run: npm run lib:build --prefix openvidu-components-angular
    - name: Build openvidu-webcomponent
      run: npm run webcomponent:build --prefix openvidu-components-angular
    - name: Build openvidu-angular-testapp
      run: npm run build --prefix openvidu-components-angular
    - name: Run Angular Testapp
      run: npm run start-prod --prefix openvidu-components-angular &
    - name: Run Angular E2E
      run: npm run lib:e2e-ci --prefix openvidu-components-angular
    - name: Run Webcomponent Testapp
      run: npm run webcomponent:serve-testapp --prefix openvidu-components-angular &
    - name: Run Webcomponent E2E
      run:  npm run webcomponent:e2e-ci --prefix openvidu-components-angular
